enum ColorMode { LIGHT, DARK }

enum ColorType {
  PRIMARY,
}

enum ContentColor {
  PRIMARY_BUTTON_COLOR,
  PRIMARY_BUTTON_TEXT_COLOR,
  ERROR_BUTTON_COLOR,
  ERROR_BUTTON_TEXT_COLOR,
  TEXT_COLOR,
  GREY_TEXT_COLOR,
  BACKGROUND_COLOR,
  ICON_COLOR,
  PRIMARY_ICON_COLOR,
  CARD_COLOR,
  DIVIDER_COLOR,
  ERROR_COLOR,
  SUCCESS_COLOR,
  WARNING_COLOR,
  INFO_COLOR,
  DISABLED_COLOR,
  HINT_COLOR,
  FOCUS_COLOR,
  SHADOW_COLOR,
  INPUT_BACKROUND,
  INPUT_HOVER,
}
